Repository honeycombio/beeline-go, pull requests merged in 2021-11, with the labels that each got.

#284 Update libhoney-go to v1.15.6
  go.mod
  go.sum
Labels: type: maintenance, version: bump patch

#285 Prepare v1.3.1 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump patch

#287 [hnygrpc] add a human readable version of the grpc status code to auto instrumentation
  wrappers/hnygrpc/grpc.go
  wrappers/hnygrpc/grpc_test.go
Labels: type: enhancement, version: bump patch

#289 test: remove flake-prone test case
  sample/deterministic_sampler_test.go
Labels: version: no bump, type: maintenance

#291 Update dependabot to monthly
  .github/dependabot.yml
Labels: version: no bump, type: maintenance, merge at will
