Repository honeycombio/beeline-go, pull requests merged in 2021-07, with the labels that each got.

#247 Prepare 1.1.3 release
  CHANGELOG.md
  version.go
Labels: status: review needed, type: maintenance, version: bump patch

#245 Use `PingContext` in the wrapped `PingContext` method
  wrappers/hnysql/sql.go
  wrappers/hnysql/sql_test.go
Labels: status: revision needed, type: bug, version: bump patch

#249 fix(echo): this change ensures honeycomb captures errors correctly
  wrappers/hnyecho/echo.go
  wrappers/hnyecho/echo_test.go
  wrappers/hnyecho/hnyecho_test.go
Labels: type: bug, version: bump patch

#246 feat: span.AddField() support adding error
  beeline.go
  trace/trace.go
  trace/trace_test.go
Labels: status: revision needed, type: enhancement, version: bump minor
