Repository honeycombio/beeline-go, pull requests merged in 2021-05, with the labels that each got.

#217 Add gRPC UnaryClientInterceptor
  examples/grpc/main.go
  examples/grpc/proto/generate.go
  examples/grpc/proto/hello.pb.go
  examples/grpc/proto/hello.proto
  examples/grpc/proto/hello_grpc.pb.go
  go.mod
  wrappers/config/config.go
  wrappers/hnygrpc/grpc.go
Labels: status: review needed, type: enhancement

#216 Capture correct request.host value on http client redirects
  wrappers/common/common.go
  wrappers/common/common_test.go
Labels: version: bump patch

#227 Fix go.sum and CI
  .circleci/config.yml
  go.sum
Labels: type: bug, version: bump patch
