Repository honeycombio/beeline-go, pull requests merged in 2022-08, with the labels that each got.

#338 Downgrade go-sqlite3 to stable version
  go.mod
  go.sum
Labels: type: maintenance, status: oncall

#340 maint: add go 1.19 to CI
  .circleci/config.yml
Labels: version: no bump, type: maintenance, merge at will

#341 Add more request header information to GRPC handler spans
  wrappers/hnygrpc/grpc.go
  wrappers/hnygrpc/grpc_test.go
Labels: type: enhancement, version: bump minor

#342 [release] prep v1.10.0
  CHANGELOG.md
  version.go
Labels: type: maintenance, merge at will
