Repository honeycombio/beeline-go, pull requests merged in 2022-10, with the labels that each got.

#345 Include Commit/Rollback in db.call names
  wrappers/common/common.go
Labels: status: oncall

#350 [maint] Drop support for go 1.16
  .circleci/config.yml
  README.md
  go.mod
Labels: type: maintenance, version: bump minor

#351 maint: add new project workflow
  .github/workflows/add-to-project-v2.yml
Labels: version: no bump, type: maintenance

#352 [release] v1.11.0
  CHANGELOG.md
  version.go
Labels: version: no bump, type: maintenance

#354 maint: add release file
  .github/release.yml
Labels: version: no bump, type: maintenance, merge at will, no-changelog

#353 pre-define capacities for rollups and TLFs
  trace/trace.go
Labels: status: oncall

#356 Prepare v1.11.1 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, no-changelog

#357 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: version: no bump, type: maintenance, merge at will
