Repository honeycombio/beeline-go, pull requests merged in 2023-06, with the labels that each got.

#383 docs: update readme
  README.md
Labels: type: documentation, no-changelog

#385 maint: Bump libhoney to 1.19.0
  go.mod
  go.sum
Labels: type: maintenance, version: bump patch

#384 rel: Prepare v1.12.0 release
  CHANGELOG.md
  version.go
Labels: version: no bump, type: maintenance, no-changelog
