Repository honeycombio/beeline-go, pull requests merged in 2024-03, with the labels that each got.

#421 feat: support classic Ingest Keys
  beeline.go
  go.mod
  go.sum
Labels: type: enhancement, version: bump minor

#425 rel: Prepare 1.15.0 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, no-changelog

#426 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: version: no bump, type: maintenance, no-changelog

#432 maint: drop go 1.18
  .circleci/config.yml
  README.md
  go.mod
Labels: type: maintenance, version: bump minor
